POST http://localhost:3000/account
Content-Type: application/json

{
  "firstName": "Andre",
  "lastName": "Nakashima"
}

###
GET http://localhost:3000/account


###
GET http://localhost:3000/account/2

###
DELETE http://localhost:3000/account/2